-- AlterTable
ALTER TABLE "criadores" ALTER COLUMN "sementes" SET DEFAULT 0,
ALTER COLUMN "sementes" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "doacoes" ALTER COLUMN "quantidade" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "usuarios" ALTER COLUMN "sementes" SET DEFAULT 0,
ALTER COLUMN "sementes" SET DATA TYPE DOUBLE PRECISION;
